/* WildVenture Tourist Packages - editable package catalog */
const TOURIST_PACKAGES = [
 {id:'tadoba-wildlife-safari',name:'Tadoba Wildlife Safari',location:'Tadoba Andhari Tiger Reserve, Chandrapur',state:'Maharashtra',duration:'2 Days / 1 Night',price:4499,activities:['Jeep Safari','Wildlife Photography'],description:'Track the wild heart of Tadoba with guided jeep safaris, forest landscapes and dedicated wildlife photography opportunities.',image:'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Tadoba+Andhari+Tiger+Reserve+Chandrapur+Maharashtra'},
 {id:'mahabaleshwar-adventure',name:'Mahabaleshwar Adventure',location:'Mahabaleshwar, Satara',state:'Maharashtra',duration:'3 Days / 2 Nights',price:5499,activities:['Trekking','Camping','Waterfalls'],description:'A refreshing Sahyadri escape combining forest trails, scenic waterfalls, campsite nights and panoramic hill views.',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Mahabaleshwar+Satara+Maharashtra'},
 {id:'lonavala-camping',name:'Lonavala Camping',location:'Lonavala, Pune',state:'Maharashtra',duration:'2 Days / 1 Night',price:3999,activities:['Camping','Trekking','Sightseeing'],description:'Spend a night in the Sahyadris with easy-going treks, misty viewpoints and classic Lonavala sightseeing.',image:'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Lonavala+Pune+Maharashtra'},
 {id:'pench-wildlife-adventure',name:'Pench Wildlife Adventure',location:'Pench Tiger Reserve',state:'Maharashtra / Madhya Pradesh',duration:'3 Days / 2 Nights',price:6499,activities:['Jeep Safari','Bird Watching'],description:'Explore Pench landscapes on jeep safaris and slow down for birding sessions across one of central India’s famous forests.',image:'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Pench+Tiger+Reserve+Maharashtra+Madhya+Pradesh'},
 {id:'melghat-jungle-escape',name:'Melghat Jungle Escape',location:'Melghat Tiger Reserve, Amravati',state:'Maharashtra',duration:'3 Days / 2 Nights',price:5799,activities:['Safari','Nature Trails'],description:'Reconnect with the forest through safari drives and guided nature trails in the rugged Satpura landscape of Melghat.',image:'https://images.unsplash.com/photo-1535338454770-8be927b5a00b?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Melghat+Tiger+Reserve+Amravati+Maharashtra'},
 {id:'tarkarli-beach-adventure',name:'Tarkarli Beach Adventure',location:'Tarkarli, Sindhudurg',state:'Maharashtra',duration:'3 Days / 2 Nights',price:6999,activities:['Scuba Diving','Water Sports'],description:'Take the adventure to the Konkan coast with underwater exploration, water sports and laid-back Tarkarli beach time.',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Tarkarli+Sindhudurg+Maharashtra'},
 {id:'lonar-crater-explorer',name:'Lonar Crater Explorer',location:'Lonar, Buldhana',state:'Maharashtra',duration:'2 Days / 1 Night',price:4299,activities:['Crater Lake','Nature & Heritage'],description:'Discover the remarkable Lonar landscape through crater-lake views, nature walks and nearby heritage exploration.',image:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Lonar+Crater+Lake+Buldhana+Maharashtra'},
 {id:'bhandardara-camping',name:'Bhandardara Camping',location:'Bhandardara',state:'Maharashtra',duration:'2 Days / 1 Night',price:3499,activities:['Camping','Trekking','Lake Views'],description:'Camp beside the Sahyadri lake country with relaxed treks, stargazing and beautiful Bhandardara viewpoints.',image:'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Bhandardara+Maharashtra'},
 {id:'chikhaldara-hill-adventure',name:'Chikhaldara Hill Adventure',location:'Chikhaldara, Amravati',state:'Maharashtra',duration:'3 Days / 2 Nights',price:4999,activities:['Trekking','Waterfalls','Wildlife'],description:'A cool-climate hill adventure featuring forest trails, seasonal waterfalls, viewpoints and wildlife experiences.',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Chikhaldara+Amravati+Maharashtra'},
 {id:'panchgani-escape',name:'Panchgani Escape',location:'Panchgani, Satara',state:'Maharashtra',duration:'2 Days / 1 Night',price:4599,activities:['Paragliding','Table Land','Sightseeing'],description:'Soar above the hills, explore the iconic Table Land and enjoy a compact Panchgani getaway packed with views.',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80',maps:'https://www.google.com/maps/search/?api=1&query=Panchgani+Satara+Maharashtra'}
];

const TouristPackages = {
 render(){
  const grid=document.getElementById('tourist-packages-grid'); if(!grid)return;
  const query=(document.getElementById('package-search')?.value||'').toLowerCase().trim();
  const list=TOURIST_PACKAGES.filter(p=>!query||`${p.name} ${p.location} ${p.state} ${p.activities.join(' ')}`.toLowerCase().includes(query));
  document.getElementById('packages-results-count').textContent=`${list.length} package${list.length===1?'':'s'} available`;
  grid.innerHTML=list.map((p,i)=>`<article class="package-card"><div class="package-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="package-number">${String(i+1).padStart(2,'0')}</span><span class="package-price">₹${p.price.toLocaleString()} <small>/ person</small></span></div><div class="package-body"><div class="package-location"><i class="ph ph-map-pin"></i><span>${p.location}<br>${p.state}</span></div><h3 class="package-title">${p.name}</h3><p class="package-desc">${p.description}</p><div class="package-meta"><span><i class="ph ph-calendar"></i> ${p.duration}</span><span><i class="ph ph-tag"></i> Adventure Package</span></div><div class="package-activities">${p.activities.map(a=>`<span class="activity-pill">${a}</span>`).join('')}</div><div class="package-actions"><button class="btn btn-primary btn-sm" onclick="TouristPackages.book('${p.id}')"><i class="ph ph-ticket"></i> Book Now</button><button class="btn btn-outline btn-sm" onclick="TouristPackages.openDetails('${p.id}')"><i class="ph ph-eye"></i> View Details</button><a class="btn btn-outline btn-sm package-map" href="${p.maps}" target="_blank" rel="noopener"><i class="ph ph-map-trifold"></i> View Location / Google Maps</a></div></div></article>`).join('')||`<div class="empty-state-card col-span-full"><i class="ph ph-magnifying-glass empty-icon"></i><h3>No packages found</h3><p>Try another destination or package name.</p></div>`;
 },
 openDetails(id){
  const p=TOURIST_PACKAGES.find(x=>x.id===id); if(!p)return;
  const modal=document.getElementById('tourist-package-modal');
  document.getElementById('package-detail-content').innerHTML=`<div class="package-detail-grid"><div><img class="package-detail-image" src="${p.image}" alt="${p.name}"></div><div class="package-detail-copy"><span class="section-tag"><i class="ph ph-compass"></i> Tourist Package</span><h2>${p.name}</h2><div class="package-location"><i class="ph ph-map-pin"></i><span>${p.location}<br>${p.state}</span></div><p>${p.description}</p><div class="package-detail-facts"><div class="package-fact"><strong>Duration</strong>${p.duration}</div><div class="package-fact"><strong>Price</strong>₹${p.price.toLocaleString()} / person</div></div><h4>Main Activities</h4><div class="package-detail-activities">${p.activities.map(a=>`<span class="activity-pill">${a}</span>`).join('')}</div><div class="package-detail-actions"><button class="btn btn-primary" onclick="TouristPackages.book('${p.id}')"><i class="ph ph-ticket"></i> Book Now</button><a class="btn btn-outline" href="${p.maps}" target="_blank" rel="noopener"><i class="ph ph-map-trifold"></i> Google Maps</a></div></div></div>`;
  modal.classList.add('active'); document.body.style.overflow='hidden';
 },
 closeDetails(){document.getElementById('tourist-package-modal')?.classList.remove('active');document.body.style.overflow='auto'},
 book(id){
  const p=TOURIST_PACKAGES.find(x=>x.id===id); if(!p)return;
  // Use the existing booking/payment flow without changing its implementation.
  const campsite={id:`package-${p.id}`,title:p.name,location:`${p.location}, ${p.state}`,pricePerNight:p.price,contractor:{id:'package-operator',name:'WildVenture Tourist Packages'},image:p.image,amenities:p.activities,difficulty:'Moderate',altitude:'—',bestSeason:'Seasonal',availableSlots:20,tagline:p.description,coordinates:'',rating:5,reviewsCount:0,contractor:{id:'package-operator',name:'WildVenture Tourist Packages',leadGuide:'WildVenture Guide Team',phone:'+91 00000 00000',badge:'Verified Package',verified:true},itinerary:[{day:'Day 1',title:'Arrival & Adventure',desc:`Experience ${p.activities[0]}.`},{day:'Day 2',title:'Explore & Depart',desc:`Enjoy ${p.activities.slice(1).join(', ')} and complete your getaway.`}]};
  TouristPackages.closeDetails();
  if(window.App && typeof App.openCampsiteModal==='function'){
   // Temporarily expose the package as a campsite so the existing checkout widget can be reused.
   App.activeCampsiteModal=campsite; App.selectedGearForBooking=[];
   App.openCampsiteModal = App.openCampsiteModal; // preserve existing method reference
   // Populate the existing booking modal through the same UI path by injecting a transient record.
   const campsites=DB.get('campsites')||[]; campsites.unshift(campsite); DB.set('campsites',campsites); App.openCampsiteModal(campsite.id);
   window.__wildVenturePackageBookingId=campsite.id;
  } else showToast('Booking system is unavailable. Please use the existing Campsites & Treks booking flow.','warning');
 }
};

document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('package-search');input?.addEventListener('input',()=>TouristPackages.render());TouristPackages.render();});
window.TOURIST_PACKAGES=TOURIST_PACKAGES;window.TouristPackages=TouristPackages;
